// chatserver-generated
// Basic inspriation: https://socket.io/how-to/use-with-react
const express = require('express');
const http = require('http');
const socketIo = require('socket.io');

const router = express.Router();
const server = http.createServer(router);
const io = socketIo(server);

let messages = {};
const welcomeMessage = { text: 'Welcome to the chat!', timestamp: new Date().toISOString(), editable: false};

io.on('connection', (socket) => {
    console.log('New client connected');

    socket.on('join', (pinId) => {
        socket.join(pinId);

        if (!messages[pinId]) {
            messages[pinId] = [welcomeMessage];
        }

        socket.emit('init', messages[pinId]);
    });

    socket.on('message', (message) => {
        const { pinId } = message;

        if (!messages[pinId]) {
            messages[pinId] = [];
        }

        messages[pinId].push(message);
        io.to(pinId).emit('message', message);
    });

    // This segment was generated by ChatGTP on June 28nd, 2024'
    // The prompt used was: how to make a edit a message in a chatbox.
    // modifcations were made to intergrate it to the porject. One such major modification made was to make it so each pin is treated differently
    socket.on('edit-message', (editedMessage) => {
        const { pinId, id } = editedMessage;

        if (messages[pinId]) {
            messages[pinId] = messages[pinId].map((msg) =>
                msg.id === id ? editedMessage : msg
            );
            io.to(pinId).emit('edit-message', editedMessage);
        }
    });

    socket.on('delete-message', ({ pinId, messageId }) => {
        if (messages[pinId]) {
            messages[pinId] = messages[pinId].filter((msg) => msg.id !== messageId);
            io.to(pinId).emit('delete-message', { pinId, messageId });
        }
    });

    socket.on('leave', (pinId) => {
        socket.leave(pinId);
    });

    socket.on('disconnect', () => {
        console.log('Client disconnected');
    });
});

server.listen(4000, () => {
    console.log('Server is running on port 4000');
});


module.exports = router;