import React, { useState } from 'react';
import ChatInput from './ChatInput.jsx';
import ChatMessages from './ChatMessages.jsx';


{/* stuff marked with "chat-generated" was generated by ChatGTP on June 20st, 2024'
          The prompt used was: how to make a local chatbox in react
         modifcations were made to intergrate it to the porject, put most of the structure remains intact */}
const ChatBox = () => {
    const [messages, setMessages] = useState([]);

    const addMessage = (message) => {
        setMessages([...messages, message]);
    };

    return (
        <div className="chat-box">
            <ChatMessages messages={messages} />
            <ChatInput addMessage={addMessage} />
        </div>
    );
};

export default ChatBox;