import React from 'react';
import { MapContainer, TileLayer, Marker, Popup } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';

/*
'The structure of this code was generated by ChatGTP on June 5th, 2024'
The prompt used was: react using leaflet api
This was heavly adapted to fit our project spec. The styling was nice so also used from what was generated. 
*/
const MapInterface = () => {

    return (
        <div style={{ display: 'flex', justifyContent: 'center' }}>
        <MapContainer center={[49.2606, -123.2460]} zoom={14} style={{ height: "700px", width: "50%" }}>
          <TileLayer
            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            maxZoom={19}
          />
          <Marker position={[49.2663889 , -123.2497222]}>
            <Popup>
              <b>The Nest</b><br />Food is rly mid
            </Popup>
          </Marker>
        </MapContainer>
        </div>
      );
};

export default MapInterface;