import React, { useState, useEffect } from 'react';
import io from 'socket.io-client';
import ChatInput from './ChatInput.jsx';
import ChatMessages from './ChatMessages.jsx';
import { v4 as uuidv4 } from 'uuid';
import { useSelector } from 'react-redux';


{/* stuff marked with "chat-generated" was generated by ChatGTP on June 20st, 2024'
          The prompt used was: how to make a local chatbox in react
         since inital genration has been heavily modified toi fit the needs of the porject*/}
{/* stuff marked with "chatserver-generated" was generated by ChatGTP on June 22nd, 2024'
          The prompt used was: how to make a local chatbox appear on other local intances.
         modifcations were made to intergrate it to the porject, put most of the structure remains intact */}

//connect the chatbox to the server
const socket = io('https://ubcstudyspotterserver.onrender.com', {
    transports: ['websocket', 'polling', 'flashsocket']
});

const userId = localStorage.getItem('userId') || uuidv4();
localStorage.setItem('userId', userId);

//given pinID, managae the chatBox for that particular pin
const ChatBox = ({ pinId }) => {
    const [messages, setMessages] = useState([]);
    
    //only enable the chat when user is signed in
    const isAuthenticated = useSelector((state) => state.auth.isAuthenticated);

    useEffect(() => {
        //when joining the server, define the userID and tell it which pin is connecting
        socket.emit('join', { pinId, userId });

        //send all the all messages that have been sent already to a new client that has joined
        socket.on('init', (initialMessages) => {
            const parsedMessages = initialMessages.map((msg) => ({
                ...msg,
                timestamp: new Date(msg.timestamp)
            }));
            setMessages(parsedMessages);
        });

        //on message, add it to the list of messages for that chatBox
        socket.on('message', (message) => {
            const parsedMessage = {
                ...message,
                timestamp: new Date(message.timestamp)
            };
            setMessages((prevMessages) => [...prevMessages, parsedMessage]);
        });

        //when i recived a new edited message, add it to list of server.
        socket.on('edit-message', (editedMessage) => {
            const parsedMessage = {
                ...editedMessage,
                timestamp: new Date(editedMessage.timestamp)
            };
            setMessages((prevMessages) =>
                prevMessages.map((msg) => (msg.id === editedMessage.id ? parsedMessage : msg))
            );
        });
        
        //remove message slated for deltation from list in chatBox
        socket.on('delete-message', ({ messageId }) => {
            setMessages((prevMessages) =>
                prevMessages.filter((msg) => msg.id !== messageId)
            );
        });
        
        //cleanup sockets when leaving chatbox
        return () => {
            socket.emit('leave', pinId);
            socket.off('init');
            socket.off('message');
            socket.off('edit-message');
            socket.off('delete-message');
        };
    }, [pinId]);

    //send a new message to the server. Give it a unique id in the form of uuidv4
    const addMessage = (message) => {
        const newMessage = { ...message, id: uuidv4(), pinId, userId, editable: true };
        socket.emit('message', newMessage);
    };

    //take the edited message and send it to the server
    const editMessage = (messageId, newText) => {
        const editedMessage = {
            id: messageId,
            text: newText,
            timestamp: new Date().toISOString(),
            pinId,
            userId, 
            editable: true
        };
        socket.emit('edit-message', editedMessage);
    };

    //tell the server which message to delete.
    const deleteMessage = (messageId) => {
        socket.emit('delete-message', { pinId, messageId, userId });
    };

    return (
        <div className="chat-box">
            <ChatMessages messages={messages} onEdit={editMessage} onDeleteMessage={deleteMessage} />
            {/* if authenticatd, allow messages to be sent */}
            {isAuthenticated ? (
                <ChatInput addMessage={addMessage} />
            ) : (
                <p>Please sign in to send messages!</p>
            )}
        </div>
    );
};

export default ChatBox;